#!/bin/bash
# Install + configure PostgreSQL 16 for the email index on MAIL02.
# Idempotent — safe to re-run.
#
# Steps:
#   1. Apply tuned postgresql.conf via include directive.
#   2. Append pg_hba.conf rules for scram-sha-256 from 10.0.1.0/24.
#   3. UFW allow 5432/tcp from LAN.
#   4. Create DB 'ges_mail' + extensions + schema + roles with random passwords.
#   5. Write /etc/mailinabox/postgres.env with DSNs (chmod 600).
#
# NOTE: DB + roles renamed 2026-06-19 (RUNBOOK-infra-rename.md): DB emails -> ges_mail,
#       roles email_{indexer,reader} -> ges_mail_{indexer,reader}. The TABLE is still
#       named 'emails' inside the ges_mail DB. Env-var KEYS kept (EMAIL_*_PW, PG_DSN_*).

set -euo pipefail

PG_VERSION=16
PG_CONF_DIR=/etc/postgresql/$PG_VERSION/main
PG_CONF=$PG_CONF_DIR/postgresql.conf
PG_HBA=$PG_CONF_DIR/pg_hba.conf
TUNED_CONF=$PG_CONF_DIR/conf.d/99-mailinabox-tuned.conf

SRC_DIR="$(cd "$(dirname "$0")" && pwd)"

if ! command -v psql >/dev/null; then
    echo "ERROR: psql not installed. Install postgresql-$PG_VERSION first." >&2
    exit 1
fi

echo "[+] Apply tuned postgresql.conf..."
mkdir -p "$(dirname "$TUNED_CONF")"
install -m 0644 "$SRC_DIR/postgresql.conf.tuned" "$TUNED_CONF"

# Ensure conf.d is included
if ! grep -q "^include_dir = 'conf.d'" "$PG_CONF"; then
    echo "" >> "$PG_CONF"
    echo "include_dir = 'conf.d'" >> "$PG_CONF"
fi

echo "[+] Configure pg_hba.conf..."
# Remove any prior mailinabox-managed block, then append fresh
sed -i '/# BEGIN mailinabox/,/# END mailinabox/d' "$PG_HBA"
cat >> "$PG_HBA" <<'EOF'
# BEGIN mailinabox — email index access
host    ges_mail    ges_mail_indexer    10.0.1.0/24    scram-sha-256
host    ges_mail    ges_mail_reader     10.0.1.0/24    scram-sha-256
host    ges_mail    ges_mail_indexer    127.0.0.1/32   scram-sha-256
host    ges_mail    ges_mail_reader     127.0.0.1/32   scram-sha-256
# END mailinabox
EOF

echo "[+] UFW allow 5432 from LAN..."
if command -v ufw >/dev/null && ufw status | grep -q "Status: active"; then
    ufw allow from 10.0.1.0/24 to any port 5432 proto tcp comment 'PostgreSQL email index'
fi

echo "[+] Restart PostgreSQL..."
systemctl restart postgresql@$PG_VERSION-main

echo "[+] Wait for PG ready..."
for i in {1..30}; do
    if sudo -u postgres psql -c "SELECT 1" >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

# Generate or reuse passwords
ENV_FILE=/etc/mailinabox/postgres.env
mkdir -p /etc/mailinabox
if [[ -f $ENV_FILE ]]; then
    # shellcheck disable=SC1090
    . $ENV_FILE
    echo "[+] Reusing existing passwords from $ENV_FILE"
else
    EMAIL_INDEXER_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
    EMAIL_READER_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
fi

echo "[+] Create database (if missing)..."
DB_EXISTS=$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='ges_mail'")
if [[ "$DB_EXISTS" != "1" ]]; then
    sudo -u postgres createdb -E UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --template=template0 ges_mail
fi

echo "[+] Create roles..."
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ges_mail_indexer') THEN
        CREATE ROLE ges_mail_indexer LOGIN PASSWORD '$EMAIL_INDEXER_PW';
    ELSE
        ALTER ROLE ges_mail_indexer LOGIN PASSWORD '$EMAIL_INDEXER_PW';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ges_mail_reader') THEN
        CREATE ROLE ges_mail_reader LOGIN PASSWORD '$EMAIL_READER_PW';
    ELSE
        ALTER ROLE ges_mail_reader LOGIN PASSWORD '$EMAIL_READER_PW';
    END IF;
END \$\$;

GRANT CONNECT ON DATABASE ges_mail TO ges_mail_indexer, ges_mail_reader;
SQL

echo "[+] Apply schema in 'ges_mail' database..."
sudo -u postgres psql -v ON_ERROR_STOP=1 -d ges_mail -f "$SRC_DIR/schema.sql"

echo "[+] Grant table privileges + transfer ownership to indexer..."
sudo -u postgres psql -v ON_ERROR_STOP=1 -d ges_mail -f "$SRC_DIR/grant_ownership.sql"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d ges_mail <<'SQL'
GRANT SELECT, INSERT, UPDATE, DELETE ON emails, indexer_meta TO ges_mail_indexer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ges_mail_indexer;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ges_mail_indexer;
GRANT SELECT ON emails, indexer_meta TO ges_mail_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ges_mail_reader;
SQL

echo "[+] Write env file $ENV_FILE..."
# Write FULLY EXPANDED values (no bash variable references) so systemd
# EnvironmentFile= can use them directly — systemd does NOT do shell expansion.
cat > $ENV_FILE <<EOF
# PostgreSQL DSNs for the email index — generated by install.sh
EMAIL_INDEXER_PW=$EMAIL_INDEXER_PW
EMAIL_READER_PW=$EMAIL_READER_PW
PG_DSN_INDEXER=postgresql://ges_mail_indexer:$EMAIL_INDEXER_PW@127.0.0.1:5432/ges_mail
PG_DSN_READER=postgresql://ges_mail_reader:$EMAIL_READER_PW@127.0.0.1:5432/ges_mail
# LAN access form (used from GES051WS, etc):
PG_DSN_INDEXER_LAN=postgresql://ges_mail_indexer:$EMAIL_INDEXER_PW@10.0.1.89:5432/ges_mail
PG_DSN_READER_LAN=postgresql://ges_mail_reader:$EMAIL_READER_PW@10.0.1.89:5432/ges_mail
EOF
chmod 600 $ENV_FILE
chown root:root $ENV_FILE

echo "[+] Smoke test (local + LAN)..."
sudo -u postgres psql -d ges_mail -c "SELECT count(*) AS rows_emails FROM emails;"
PGPASSWORD=$EMAIL_READER_PW psql -h 127.0.0.1 -U ges_mail_reader ges_mail -c "SELECT version();" | head -3

echo "[+] Done."
echo
echo "DSNs available in $ENV_FILE"
echo "Apply LAN client DSNs from PG_DSN_*_LAN exports."
